[package]
name = "grin_seeder_config"
version = "0.1.0"
authors = ["Quentin Le Sceller <q.lesceller@gmail.com>"]
workspace = ".."

[dependencies]
grin_seeder_dns_server = { path = "../dns_server"}
grin_seeder_util = { path = "../util"}

serde = "~1.0.8"
serde_derive = "~1.0.8"
toml = "0.4"
